#!/bin/bash
# tomiia's bazar: https://github.com/tomiia/bazar
# LICENSE: WTFPL http://www.wtfpl.net/ 
# HorribleSubs: http://horriblesubs.info/
#
# This script use nyaa.se RSS feed for HorribleSubs releases via rsstail ( http://www.vanheusden.com/rsstail/ ),
# it uses a filter file for anime names, full or partial name (but need to match name in rsstail, take precaution)
# and an .error file that lists aria2c exits codes.
#
# Don't forget to edit for your needs

folder="${HOME}/Divers/Manga"
log="${folder}/.log"
filter="${folder}/.filter"
errorfile="${folder}/.error"

exit_print() {
    printf "\"%s\" episode %s : $(grep "^${exitcode} .*$" "${errorfile}" | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}')\n\n" "${name}" "${ep}"
}

clear;tmux clearhist -t downloads:2.1

rsstail -PlHNr -u 'http://www.nyaa.se/?page=rss&cats=1_37&user=64513&term=720p+-batch' 2>/dev/null | \

while read -r anime; do

    read -r url

    if grep --quiet --file="${filter}" <<< ${anime}; then
        name="$(sed -r 's/[^ ]+ (.*) - [^-]+/\1/' <<< ${anime})"
        ep=$(sed -r 's/.* - ([^ ]+) [^-]+/\1/' <<< ${anime})
        dldir="${folder}/${name}"
        
        if [ ! -e "${dldir}" ]; then
            mkdir -p "${dldir}" || printf "%s\n" "ERROR \"${dldir}\""
        fi
        
        aria2c --quiet=true --dir="${dldir}" "${url}"
        exitcode="$?"

        exit_print

    fi

done # > "${log}" 2>&1 # Uncomment if you want to use a log file instead
