#!/bin/dash

if [ $# -eq 3 ]; then

dir="${HOME}/.pyload/Downloads/Manga/$3"

if [ -e "${dir}" ]; then
	printf "%s\n" "$3 already exists"
else
	mkdir "${dir}"
fi

cd "${dir}" || exit 1

curl -s "$2" | grep -E "Horrible.*$1" | grep -v 'Batch' | sed -nr 's/^.*href="(magnet:[^"]*)".*$/\1/p' | tac | while read line
do
	aria2c "$line"
	sleep 2
done

else
        printf "%s\n" 'Usage: haruhidl quality($1) url($2) folder($3)'
        exit 1
fi
